name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

   
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Use Node.js18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Run unit tests for the app
      run: npm run test:unit
    - name: Display username
      run: echo "m.angelchova"


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

  run-ui-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Use Node.js18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install 
    - name: Run ui tests for the app
      run: npm run test:ui